config/routes.rb
Rails.application.routes.draw do

  # , except: :new
    devise_for :users
    root 'hostelp#index'
    resources :hostelp, only: :index
    resources :users, only: :show
    resources :rooms do
        
      collection do
        post 'confirm'
      end
      resources :items
    end
      

    resources :directions #使ってない


    get  'rooms/:user_name/:id'      =>  'rooms#guest_show'
    get  'items/new/:id'              =>'items#new'

        #外部公開用にパスからキーを引っ張る
end

app/models/direction.rb
class Direction < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :item
  mount_uploader :t_photo, TPhotoUploader
  mount_uploader :htgr_img, TPhotoUploader
  mount_uploader :htgk_img, TPhotoUploader
  mount_uploader :garbage, TPhotoUploader
  mount_uploader :aircon, TPhotoUploader
  # has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }
  # validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
      def new
    @direction = Direction.new
    end

    def create
    @direction = Direction.new(create_params)
    @direction.user_name = current_user.nickname
    @direction.save
    end

    private
    def create_params
      params.require(:direction).permit(:photo_no, :text,)
    end
end

app/controllers/hostelp_controller.rb
class HostelpController < ApplicationController
    before_action :authenticate_user!
    # ログインしていない時にログイン画面に飛ばす。
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
# binding.pry
    @room = Room.find(params[:room_id])
    @items = Item.where(room_no:params[:room_id]).order('photo_no ASC')
  end

  # GET /items/new
  def new
    # binding.pry
    @room = Room.find(params[:room_id])
    @item = Item.new

  end

  # GET /items/1/edit
  def edit
        @room = Room.find(params[:room_id])
    @items = Item.where(room_no:params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_name = current_user.nickname
    @item.room_no = params[:room_id]
    @item.save
    @items = Item.where(room_no: @item.room_no).order('photo_no ASC')
    # binding.pry
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    redirect_to :action => "show"
    @item.update(item_params)
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :image,:photo_no)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
before_action :authenticate_user!, except: :guest_show

  before_filter :authenticate, only: :guest_show

  def authenticate
    user = params[:user_name]
    @room = Room.find(params[:id])
    password = @room.password
    authenticate_or_request_with_http_basic('Administration') do |username, password|
    username == user && password == password
    end
  end

  def new
    @room = Room.new
  end

  def confirm
    @room = Room.new(create_params)
  end

  def create

    @room = Room.new(create_params)
    @room.user_id   = current_user.id
    @room.user_name = current_user.nickname
    @room.save
        # binding.pry
  end


  def show
    @room = Room.find(params[:id])
    @items = Item.where(room_no:params[:id])
  end

  def guest_show
    user = params[:user_name]
    id = params[:id]
    @room = Room.find(id)
    @items = Item.where(user_name: user, room_no: id).order('photo_no')
  end




  def edit
     id = params[:id]
     @room = Room.find(id)
  end

  def update
      room = Room.find(params[:id])
      room.update(update_params)
      # redirect_to 'user/show'
  end

  def destroy
      room = Room.find(params[:id])
      room.destroy
  end




  private
    def create_params
      params.require(:room).permit(:room_name, :room_no, :t_photo, :zip_code, :address_en, :address_jp, :password, :htgr, :htgk, :gmap, :aircon, :garbage, :htgr_img, :htgk_img, :google, :twitter)
    end

    def update_params
      params.require(:room).permit(:room_name, :room_no, :t_photo, :zip_code, :address_en, :address_jp, :password, :htgr, :htgk, :gmap, :aircon, :garbage, :htgr_img, :htgk_img, :google, :twitter)
    end

    # def direction_params
    #   params.require(:direction).permit(:photo_no, :text)
    # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @rooms = Room.where(user_name: current_user.nickname)
    @number = 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/hostelp_helper.rb
module HostelpHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/directions/_form.html.erb
<%= form_for(@direction) do |f| %>
  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direction.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @direction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directions/create.html.erb
<p>投稿が完了しました！</p>
<a href="/users/current_user.id>">マイページで確認。</a>

app/views/directions/new.html.erb
<%= form_for @direction do |f| %>
  <div>
    <%= f.label :photo_no, "写真番号" %><br>
    <%= f.text_field :photo_no %><br>
    <%= f.label :text, "説明文" %><br>
    <%= f.text_field :text %><br>
  </div>

  <div>
  <%= f.submit "送信", class: "btn btn-primary withripple" %>
  </div>

  

<% end %>

app/views/hostelp/index.html.erb
<h1>Hostelp</h1>

      <% if user_signed_in? %>
        <div>
          <span><p><%= current_user.nickname %>さんおかえりなさい</p>
            <ul>
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
        </div>
      <% end %>

      <div>
        <p>ここにお知らせとかを書いていく。</p>
      </div>

app/views/items/_form.html.erb
<%= form_for [@room, @item] do |f| %>

  <div class="field">
    <%= f.label :photo_no, "写真の番号（番号順に並びます。）" %><br>
    <%= f.text_area :photo_no %><br>
    <%= f.label :description, "道案内の説明を書いていきます。" %><br>
    <%= f.text_area :description %><br>
    <%= f.label :image, "道案内写真を一枚ずつアップロードしていきます。" %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/create.html.erb
<div>
  <p>写真が追加されました！</p>
</div>

<div>
  <% @items.each do |ite| %>
    <%= ite.description %><BR>
    <%= image_tag ite.image.url, :width => '400', :height => '280' %><BR>
  <% end %>
</div>

<div>
<a href="/rooms/<%= @item.room_no %>/items/new">写真の追加</a><br>
<a href="/rooms/<%= @item.room_no %>">プレビューへ</a>
</div>

app/views/items/destroy.html.erb
削除されました。
<a href="/rooms/<%= @item.room_no %>">プレビューへ</a>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= image_tag item.image.url %></td>
        <td><%= link_to 'Show',  %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>道案内を作成します。</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<div>
  <p>写真が追加されました！</p>
</div>

<div>
  <% @items.each do |ite| %>
    <%= ite.description %><BR>
    <%= image_tag ite.image.url, :width => '400', :height => '280' %><BR>
  <% end %>
</div>

<div>
<a href="/rooms/<%= @room.id %>/items/new">写真の追加</a><br>
<a href="/rooms/<%= @room.id %>">プレビューへ</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hostelp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for [@room] do |f| %>

  <div class="field">
    <%= f.label :t_photo, "Airbnbのタイトルのような写真を入れましょう" %><br>
    <%= f.file_field :t_photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/confirm.html.erb
<%= form_for [@user, @room] do |f| %>
  <div>
    部屋の名前: <%= @room.room_name %>
    <%= f.hidden_field :room_name %>
  </div>
  <div>
    郵便番号: <%= @room.zip_code %>
    <%= f.hidden_field :zip_code %>
  </div>
  <div>
    住所（英語）: <%= @room.address_en %>
    <%= f.hidden_field :address_en %>
  </div>
  <div>
    住所（日本語）: <%= @room.address_jp %>
    <%= f.hidden_field :address_jp %>
  </div>
  <div>
    部屋番号: <%= @room.room_no %>
    <%= f.hidden_field :room_no %>
  </div>
  <div>
    パスワード: <%= @room.password %>
    <%= f.hidden_field :password %>
  </div>
  <div>
    How to get the room: <%= @room.htgr %>
    <%= f.hidden_field :htgr %>
  </div>
  <div>
    How to get the key: <%= @room.htgk %>
    <%= f.hidden_field :htgk %>
  </div>
  <div>
    Google map: <%= @room.google %>
    <%= f.hidden_field :google %>
  </div>
    <div>
    Twitter: <%= @room.twitter %>
    <%= f.hidden_field :twitter %>
  </div>




  <div>
    <p>上記の内容で良ければ表題になる写真を投稿しましょう。</p>
    <p>修正したい場合はブラウザの「戻る」ボタンで戻ってください。</p>
  <div class="field">
    <%= f.label :t_photo, "Airbnbのタイトルのような写真を入れましょう" %><br>
    <%= f.file_field :t_photo %><BR><BR>

    <%= f.label :hgtr_img, "部屋への行き方の画像があれば入れましょう（周辺地図など）" %><br>
    <%= f.file_field :htgr_img %><BR><BR>
    
    <%= f.label :htgk_img, "鍵の開け方の資料を入れましょう。" %><br>
    <%= f.file_field :htgk_img %><BR><BR>
    <%= f.label :aircon, "エアコンのガイドを入れましょう。" %><br>
    <%= f.file_field :aircon %><BR><BR>
    <%= f.label :garbage, "ゴミの出し方のガイドを入れましょう。" %><br>
    <%= f.file_field :garbage %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/create.html.erb
<p>投稿完了しました。</p>
<div><!-- 登録済みの部屋一覧 -->
  <%= @room.room_name %><br>
  <%= @room.room_no %><br>
  <%= image_tag @room.t_photo.url %>

  
</div>

<a href="rooms/<%= @room.id %>/items/new">STEP2へ</a>

app/views/rooms/destroy.html.erb
<p>Lisitingが削除されました！</p>
<a href="/users/show">My pageへ戻る</a><br>

app/views/rooms/edit.html.erb
<h1>編集画面</h1>
<%= form_for @room do |f| %>
  <div>
      <%= f.label :room_name, "部屋の名前" %><br>
      <%= f.text_field :room_name, placeholder: '例：新宿のお部屋' %><br>
      <%= f.label :zip_code, "郵便番号" %><br>
      <%= f.text_field :zip_code, placeholder: '例：123-4567' %><br>
      <%= f.label :address_en, "住所（英語）" %><br>
      <%= f.text_field :address_en, placeholder: '例：1-1-1, Shinjuku' %><br>
      <%= f.label :address_jp, "住所（日本語）" %><br>
      <%= f.text_field :address_jp, placeholder: '例：新宿区１−１−１' %><br>
      <%= f.label :room_no, "部屋番号" %><br>
      <%= f.text_field :room_no, placeholder: '例：１０１号室' %><br>
      <%= f.label :password, "パスワード" %><br>
      <%= f.text_field :password, placeholder: 'お客様がHPを見るためのPW' %><br>
      <%= f.label :htgr, "How to get the room" %><br>
      <%= f.text_field :htgr, placeholder: '部屋への行き方を記入。' %><br>
      <%= f.label :htgk, "How to get the key" %><br>
      <%= f.text_field :htgk, placeholder: '鍵のとり方を記入' %><BR>
      ※部屋への行き方と鍵のとり方は次の画面で画像も投稿可能です。<br><BR>
      <%= f.label :google, "Google mapへリンクを貼ります。" %><br>
      <%= f.text_field :google, placeholder: 'Google mapへリンク。' %><br>
  </div>

  <div>
    <h2>写真の編集</h2>
    <h3><%= f.label :t_photo, "表題写真" %></h3>
    <%= image_tag @room.t_photo.url, :width => '400px', :height => '280px' %><BR>
    <%= f.file_field :t_photo %><BR>

    <h3><%= f.label :htgr_img, "部屋への行き方" %></h3>
    <%= image_tag @room.htgr_img.url, :width => '400px', :height => '280px' %><BR>
    <%= f.file_field :htgr_img %><BR>

    <h3><%= f.label :htgk_img, "鍵のとり方" %></h3>
    <%= image_tag @room.htgk_img.url, :width => '400px', :height => '280px' %><BR>
    <%= f.file_field :htgk_img %><BR>

    <h3><%= f.label :aircon, "エアコンの使い方" %></h3>
    <%= image_tag @room.aircon.url, :width => '400px', :height => '280px' %><BR>
    <%= f.file_field :aircon %><BR>

    <h3><%= f.label :garbage, "ゴミの出し方" %></h3>
    <%= image_tag @room.garbage.url, :width => '400px', :height => '280px' %><BR>
    <%= f.file_field :garbage %><BR>

  </div>
  <div>
  <%= f.submit "送信", class: "btn btn-primary withripple" %>
  </div>
  
<% end %>

app/views/rooms/guest_show.html.erb
<div class="guest">
  
    <div class ="top", id="top">
      <h1>Welcome to <%= @room.user_name %>'s room!</h1>
      <h2><%= @room.room_name %></h2>
      <h1><%= image_tag @room.t_photo.url, :width => '400px', :height => '280px' %></h1>
    </div><!-- top -->
  <div class="guest2">
    <div class="menu">
      <h2>Room menu</h2>
        <ul>
          <li><a href="#address">Address</a></li>
          <li><a href="#htgr">How to get the room</a></li>
          <li><a href="#htgk">How to get the key</a></li>
          <li><a href="#aircon">Air conditioner</a></li>
          <li><a href="#garbage">Garbage</a></li>
        </ul>
    </div><!-- menu -->

    <div class ="address", id="address">
      <h3>Address</h3>
        <ul>
          <li>Zip code : <%= @room.zip_code %></li>
          <li><%= @room.address_en %></li>
          <li><%= @room.address_jp %></li>
          <li><a href="<%= @room.google %>" target="_blank">Google Map</a></li>
        </ul>
    </div><!-- address -->



    <div class="htgr", id="htgr">
      <h3>How to get the Room</h3>
      <%= simple_format@room.htgr %><BR>
      <h3>Google map</h3>
      <%== @room.google %><BR>
      <h3>Vicinity map</h3>
      <%= image_tag @room.htgr_img.url, :width => '400px', :height => '280px' %><BR>
      <h3>Step-by-step direction</h3>
      <% @items.each do |item| %>
            
              <p><%= item.description %></p><br>
              <p>   <%= image_tag item.image.url, :width => '400', :height => '280' %></p><br>

            
        <% end %>
    </div><!-- htgr -->

    <div class="htgk", id="htgk">
      <h3>How to get the key</h3>
      <p><%= @room.htgk %></p>
      <h1 class="photo"><%= image_tag @room.htgk_img.url, :width => '800px', :height => '560px' %></h1><BR>
    </div>

    <div class="aircon", id="aircon">
      <h3>Air conditioner</h3>
      <h1 class="photo"><%= image_tag @room.aircon.url, :width => '800px', :height => '560px' %></h1><BR>
    </div>

    <div class="garbage", id="garbage">
      <h3>Garbage rule</h3>
        <p>IMPORTANT!</p>
          <p>PLEASE DO NOT throgh Garbages on wrong day, please check this or just keep it in the room! Thanks!</p>
      <h1 class="photo"><%= image_tag @room.garbage.url, :width => '800px', :height => '560px' %></h1><BR>
    </div>
  </div><!-- guest2 -->
  <div class="twitter">
    <%== @room.twitter %>
  </div>

</div><!-- guest -->

app/views/rooms/new.html.erb
<h1>STEP1 -基本情報入力-</h1>

<%= form_for @room, url:{action: 'confirm'} do |f| %>
  <div>
    <%= f.label :room_name, "部屋の名前" %><br>
    <%= f.text_field :room_name, placeholder: '例：新宿のお部屋', :size=>'60'%><br>
    <%= f.label :zip_code, "郵便番号" %><br>
    <%= f.text_field :zip_code, placeholder: '例：123-4567', :size=>'60' %><br>
    <%= f.label :address_en, "住所（英語）" %><br>
    <%= f.text_field :address_en, placeholder: '例：1-1-1, Shinjuku', :size=>'60' %><br>
    <%= f.label :address_jp, "住所（日本語）" %><br>
    <%= f.text_field :address_jp, placeholder: '例：新宿区１−１−１', :size=>'60' %><br>
    <%= f.label :room_no, "部屋番号" %><br>
    <%= f.text_field :room_no, placeholder: '例：１０１号室' %><br>
    <%= f.label :password, "パスワード" %><br>
    <%= f.text_field :password, placeholder: 'お客様がHPを見るためのPW', :size=>'60' %><br>
    <%= f.label :htgr, "How to get the room" %><br>
    <%= f.text_area :htgr, placeholder: '部屋への行き方を記入。' ,:size=>'60x10'%><br>
    <%= f.label :htgk, "How to get the key" %><br>
    <%= f.text_area :htgk, placeholder: '鍵のとり方を記入', :size=>'60x10' %><BR>
    ※部屋への行き方と鍵のとり方は次の画面で画像も投稿可能です。<br>
    <%= f.label :google, "Google mapの埋め込みコード" %><br>
    <%= f.text_field :google, placeholder: 'Google mapで取得したコードをコピー' , :size=>'60'%><br>
    <%= f.label :twitter, "ツイッターのURLを入力します。" %><br>
    <%= f.text_field :twitter, placeholder: 'TwitterのURL', :size=>'60' %><br>

  </div>
<!--   <div class="actions">
    <%= f.submit %>
  </div> -->
  <div>
  <BR><%= f.submit "送信", class: "btn btn-primary withripple" %>
  </div>
<% end %>

app/views/rooms/show.html.erb
<div class="kihon"><!-- 登録済みの部屋一覧 -->
  <h1>これはプレビュー画面です。</h1>
  <a href="/users/<%= current_user.id%>">マイページへ戻る</a>



  <h2>基本情報</h2>
  <a href="/rooms/<%= params[:id] %>/edit">基本情報編集</a>
  <p>ゲスト用URL（このURLをコピーしてゲストにお送りください。）</p> 
  <p>https://hostelp.herokuapp.com/rooms/<%= current_user.nickname %>/<%= @room.id %></p>
  <p>--------------------------------ここからゲストが見る画面-------------------------</p>
</div><!-- kihon -->

<div class ="preview">
    <div class = "top", id="top">
      <h1>Welcome to <%= @room.user_name %> room!</h1>
      <h2><%= @room.room_name %></h2>
      <h1><%= image_tag @room.t_photo.url, :width => '400px', :height => '280px' %></h1>
    </div>
  <div class ="preview2">

    <div class="menu">
      <h2>Room menu</h2>
        <ul>
          <li><a href="#address">Address</a></li>
          <li><a href="#htgr">How to get the room</a></li>
          <li><a href="#htgk">How to get the key</a></li>
          <li><a href="#aircon">Air conditioner</a></li>
          <li><a href="#garbage">Garbage</a></li>
        </ul>
    </div>

    <div class ="address", id="address">

      <h3>Address</h3>
        <ul>
          <li>Zip code : <%= @room.zip_code %></li>
          <li><%= @room.address_en %></li>
          <li><%= @room.address_jp %></li>
          <li><a href="<%= @room.google %>" target="_blank">Google Map</a></li>
        </ul>
    </div>



    <div class ="htgr", id="htgr">
    <h3>How to get the Room</h3>
    <%= simple_format@room.htgr %><BR>
    <h3>Google map</h3>
    <%== @room.google %><BR>
    <h3>Vicinity map</h3>
    <%= image_tag @room.htgr_img.url, :width => '400px', :height => '280px' %><BR>


     <%= link_to '道案内に写真を追加', "#{@room.id}/items/new" %><BR>
     <h3>Step-by-step direction</h3>
     <% @items.each do |item| %>
          <tr>
            <td><%= item.description %></td><br>
            <td><%= image_tag item.image.url, :width => '400', :height => '280' %></td><br>
            <td><a href="/rooms/<%= @room.id %>/items/<%= item.id %>/edit">編集</a></td>
            <td><%= link_to '削除', "/rooms/#{@room.id}/items/#{item.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td><br>
          </tr>
        <% end %>
    </div>

    <div class ="htgk", id="htgk">
      <h3>How to get the key</h3>
      <%= @room.htgk %><BR>
      <%= image_tag @room.htgk_img.url, :width => '800px', :height => '560px' %><BR>
    </div>

    <div class="aircon", id="aircon">
      <h3>Air conditioner</h3>
      <%= image_tag @room.aircon.url, :width => '800px', :height => '560px' %><BR>
    </div>

    <div class ="garbage", id="garbage">
      <h3>Garbage rule</h3>
        <p>IMPORTANT!</p>
          <p>PLEASE DO NOT throgh Garbages on wrong day, please check this or just keep it in the room! Thanks!</p>
      <%= image_tag @room.garbage.url, :width => '800px', :height => '560px' %><BR>
    </div>
  </div><!-- preview2 -->
  <div class="twitter">
    <%== @room.twitter %>
  </div>
</div><!-- preview -->

app/views/rooms/update.html.erb
<p>Lisitingが更新されました！</p>
<a href="/users/show">My pageへ戻る</a><br>

app/views/users/show.html.erb
<h1><%= current_user.nickname %>さんのマイページです</h1>

  <div><!-- 登録済みの部屋一覧 -->
    <% @rooms.each do |room| %>
    <h2 class ="mypage"><%= @number %>.<%= room.room_name %></h2>

      <%= image_tag room.t_photo.url, :width => '400px', :height => '280px' %><BR>
      <a href="/rooms/<%= room.id %>">プレビュー＆編集</a>


      <%= link_to '削除', "/rooms/#{room.id}", method: :delete, data: { confirm: 'Are you sure?' } %><br>
      <% @number += 1 %>

    <% end %>
  </div>

  <div>
    <% if @number <= current_user.qty %>
      <a href="/rooms/new">新規room作成</a>
    <% end %>
  </div>
<!--Room数が上限以上だった時に非表示にするif 分。user.rooms.count -->